export const UI = {
  tabs: {
    ariaLabel: 'Content tabs',
  },
  hero: {
    eyebrow: 'Star Wars',
    title: 'Maul',
    subtitle: 'Shadow Lord',
    description:
      'After the Clone Wars, a former Sith lord plots to rebuild his criminal empire on Janix — a planet untouched by the Empire — as he hunts a disillusioned Jedi Padawan as his new apprentice.',
    pillSeason: '2026 · 1 Season',
    pillRating: '100% Rotten Tomatoes',
    pillGenre: 'Action, Adventure, Animation',
    visitDisney: 'Visit Disney+',
    teaserTrailer: 'Teaser Trailer',
    actionTrailer: 'Action Trailer',
  },
  trailer: {
    ariaClose: 'Close trailer',
    iframeTitle: 'Teaser Trailer',
  },
  episodeGrid: {
    seasonLabel: 'Season 1',
    episodeCount: '10 Episodes · April – May 2026',
    tabEpisodes: 'Episodes',
    tabPosters: 'Posters',
    tabGallery: 'Gallery',
    tabDetails: 'Details',
    posterAriaLabel: 'View poster',
    posterAlt: 'Poster',
    galleryAriaLabel: 'View image',
    galleryAlt: 'Gallery image',
  },
  episodeModal: {
    teaserTrailer: 'Teaser Trailer',
    imdb: 'IMDb',
    ariaClose: 'Close',
    iframeTitle: 'Teaser Trailer',
    metaEpisode: 'Episode',
    metaEpisodePrefix: 'E',
    metaEpisodeSeparator: ' — ',
    metaAirDate: 'Air Date',
    metaSeason: 'Season',
    metaSeasonValue: '1 · Disney+',
  },
  detailsSection: {
    castTitle: 'Voice Cast',
    detailsTitle: 'Show Details',
  },
  srOnly: {
    newTab: '(opens in new tab)',
    separator: ' · ',
  },
  footer: {
    disneyAlt: 'Disney+',
    madeBy: 'Made by',
    domain: 'krsiak.cz',
    domainUrl: 'https://krsiak.cz/',
    disclaimer: '© Lucasfilm Animation & Disney. This is fan site only.',
  },
}
